# main.yml
name: master

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]    # main 브랜치에서 push, pull_request 이벤트가 일어났을 때 실행

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@master

      - name: Cache node modules  # node modules 캐싱
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-master-build-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy
        run: |
          aws s3 cp \
            --recursive \
            --region ap-northeast-2 \
            build s3://mywebsite-byungminkim
